/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package in.edu.ashoka.shuttle;


import com.sun.speech.freetts.Voice;
import com.sun.speech.freetts.VoiceManager;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;

/**
 *
 * @author Mayukh Nair
 */

public class ShuttleApp extends javax.swing.JFrame {

    public int screenstage=0;
    public String cardaccessAllowed="n";
    public String readerInput;
    public String cardId;
    public String name, dept, shuttle, image;
    public boolean scanloopFailsafe=false;
    SoundAlerts alert=new SoundAlerts();
    ImageParser parse=new ImageParser();
    public String waitplayedonce="n";
    public String confirmplayedonce="n";
    public String welcomeplayedonce="n";
    public String netconnissue="n";
    
    /**
     * Creates new form ShuttleApp
     */
    
    public ShuttleApp() {
        // Allows app to go full screen
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
    }
   
  
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        deptLabel = new javax.swing.JLabel();
        shuttleLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        proceedLabel = new javax.swing.JLabel();
        backgroundLabel = new javax.swing.JLabel();
        carddataField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        nameLabel.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        nameLabel.setText("Name:");
        getContentPane().add(nameLabel);
        nameLabel.setBounds(40, 200, 660, 30);

        deptLabel.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        deptLabel.setText("Department:");
        getContentPane().add(deptLabel);
        deptLabel.setBounds(40, 240, 170, 30);

        shuttleLabel.setFont(new java.awt.Font("Georgia", 0, 24)); // NOI18N
        shuttleLabel.setText("Shuttle:");
        getContentPane().add(shuttleLabel);
        shuttleLabel.setBounds(40, 280, 460, 28);
        getContentPane().add(imageLabel);
        imageLabel.setBounds(620, 240, 180, 220);

        proceedLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                proceedLabelMouseClicked(evt);
            }
        });
        getContentPane().add(proceedLabel);
        proceedLabel.setBounds(250, 580, 530, 140);

        backgroundLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png"))); // NOI18N
        backgroundLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundLabelMouseClicked(evt);
            }
        });
        getContentPane().add(backgroundLabel);
        backgroundLabel.setBounds(0, 0, 1024, 770);

        carddataField.setEditable(false);
        getContentPane().add(carddataField);
        carddataField.setBounds(90, 660, 6, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        nameLabel.setVisible(false);
        deptLabel.setVisible(false);
        shuttleLabel.setVisible(false);
        System.setProperty("mbrola.base", "C:/mbrola");
        Thread scReadThread=new Thread(new Runnable(){
            public void run(){
                while(true){
                    try{
                    {
                        carddataField.requestFocus();
                        if(screenstage==1 && scanloopFailsafe==false){                        
                        readerInput=carddataField.getText();
                        Thread.sleep(200);
                        if(readerInput.length()==16){
                            System.out.println("Intact data capture");
                            cardId=readerInput;
                            backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/4.png")));
                            screenstage=2;
                            cardaccessAllowed="y";
                            Thread.sleep(200);
                            if(waitplayedonce.equals("n")){
                                alert.playSound("/in/edu/ashoka/shuttle/sounds/wait.mp3");
                                waitplayedonce="y";
                            }
                        }
                        }
                    }
                }
                catch(Exception e){
                    e.printStackTrace();
                }
                }
            }
        });
        
        scReadThread.start();
        
        
        Thread scProcessThread=new Thread(new Runnable(){
            public void run(){
                while(true){
                   try{
                        {
                        System.out.println("Contacting server...");
                        DBConnection con=new DBConnection();
                        con.initConnection(cardId);
                        name=con.getName();
                        dept=con.getDepartment();
                        shuttle=con.getShuttle();
                        image=con.getImageLink();                       
                        nameLabel.setText(name);                       
                        deptLabel.setText(dept);                        
                        shuttleLabel.setText("Departing by "+shuttle);
                        if(shuttle!=null && confirmplayedonce.equals("n")){
                            nameLabel.setVisible(true);
                            deptLabel.setVisible(true);
                            shuttleLabel.setVisible(true);
                            backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/3.png")));
                            imageLabel.setIcon(parse.getScaledImage(image, imageLabel.getWidth(), imageLabel.getHeight()));
                            screenstage=3;
                                alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                                Thread.sleep(1000);
                                VoiceManager vm=VoiceManager.getInstance();
                                Voice vo=vm.getVoice("mbrola_us1");
                                vo.allocate();
                                vo.speak(name+" from "+dept+" departing by shuttle name "+shuttle);
                                Thread.sleep(100);
                                alert.playSound("/in/edu/ashoka/shuttle/sounds/confirm.mp3");
                                confirmplayedonce="y";
                        }
                    }
                   }
                        catch(Exception e){   
                            e.printStackTrace();
                                }
                }
            }
        });
        scProcessThread.start();
    }//GEN-LAST:event_formWindowOpened

    private void proceedLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_proceedLabelMouseClicked
        // TODO add your handling code here:
       switch(screenstage){
           case 0: backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/2.png")));
                   screenstage=1;
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                   scanloopFailsafe=false;
                   carddataField.setText("");
                   carddataField.setEditable(true);
       {
           try {
               TimeUnit.SECONDS.sleep(1);
           } catch (InterruptedException ex) {
               Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/scancard.mp3");
                   break;
           case 1: backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                   screenstage=0;                  
                   carddataField.setText("");
                   carddataField.setEditable(false);
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/goback.mp3");
                   break;
           case 2: backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                   screenstage=0;
                   cardaccessAllowed="n";
                   cardId="";                   
                   scanloopFailsafe=true;
                   carddataField.setText("");
                   carddataField.setEditable(false);
                   nameLabel.setVisible(false);
                   deptLabel.setVisible(false);
                   shuttleLabel.setVisible(false);
                   imageLabel.setVisible(false);
                   name="";
                   dept="";
                   shuttle="";
                   image="";
                   waitplayedonce="n";
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/goback.mp3");
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/cancel.mp3");
                   break;
           case 3:                   
               nameLabel.setVisible(false);
                deptLabel.setVisible(false);
                shuttleLabel.setVisible(false);
                imageLabel.setVisible(false); 
                Thread screenstatusThread=new Thread(new Runnable(){
                    public void run(){
                        alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                 backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/7.png")));
                 screenstage=2;
                alert.playSound("/in/edu/ashoka/shuttle/sounds/checkingin.mp3");
                DBConnection dbc=new DBConnection();
                dbc.recordCheckIn(cardId,shuttle);
                        try {
                            Thread.sleep(5000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
                        }
               backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/5.png"))); 
                    alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                    alert.playSound("/in/edu/ashoka/shuttle/sounds/success.mp3");
                        try {
                            Thread.sleep(5000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                    screenstage=0;
                    }
                });
                screenstatusThread.start();
           break;
           default: break;
       }
    }//GEN-LAST:event_proceedLabelMouseClicked

    private void backgroundLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundLabelMouseClicked
        // TODO add your handling code here:
      switch(screenstage){
           case 0:     if(welcomeplayedonce.equals("n")){
                       alert.playSound("/in/edu/ashoka/shuttle/sounds/welcome.mp3");
                       welcomeplayedonce="y";
                       break;
                   }
                   if(welcomeplayedonce.equals("y")){
                       backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/2.png")));
                   screenstage=1;
                       alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                   scanloopFailsafe=false;
                   carddataField.setText("");
                   carddataField.setEditable(true);
                   welcomeplayedonce="n";
       {
           try {
               TimeUnit.SECONDS.sleep(1);
           } catch (InterruptedException ex) {
               Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
           }
       }
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/scancard.mp3");
                   break;
                   }
           case 1: backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                   screenstage=0;                  
                   carddataField.setText("");
                   carddataField.setEditable(false);
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/goback.mp3");
                   alert.playSound("/in/edu/ashoka/shuttle/sounds/cancel.mp3");
                   break;
           case 2: backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                   screenstage=0;
                   cardaccessAllowed="n";
                   cardId="";                   
                   scanloopFailsafe=true;
                   carddataField.setText("");
                   carddataField.setEditable(false);
                   nameLabel.setVisible(false);
                   deptLabel.setVisible(false);
                   shuttleLabel.setVisible(false);
                   imageLabel.setVisible(false);
                   name="";
                   dept="";
                   shuttle="";
                   alert.playSound("/in/edu/ashoka/shuttlesounds/goback.mp3");
                   alert.playSound("/in/edu/ashoka/shuttlesounds/cancel.mp3");
                   break;
           case 3:
               nameLabel.setVisible(false);
                deptLabel.setVisible(false);
                shuttleLabel.setVisible(false);
                imageLabel.setVisible(false); 
                Thread screenstatusThread=new Thread(new Runnable(){
                    public void run(){
                        alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                 backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/7.png")));
                 screenstage=2;
                alert.playSound("/in/edu/ashoka/shuttle/sounds/checkingin.mp3");
                DBConnection dbc=new DBConnection();
                dbc.recordCheckIn(cardId,shuttle);
                        try {
                            Thread.sleep(5000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
                        }
               backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/5.png"))); 
                    alert.playSound("/in/edu/ashoka/shuttle/sounds/buttonpress.mp3");
                    alert.playSound("/in/edu/ashoka/shuttle/sounds/success.mp3");
                        try {
                            Thread.sleep(5000);
                        } catch (InterruptedException ex) {
                            Logger.getLogger(ShuttleApp.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    backgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/in/edu/ashoka/shuttle/images/1.png")));
                    screenstage=0;
                    }
                });
                screenstatusThread.start();
           break;      
           default: break;    
       }                         
    }//GEN-LAST:event_backgroundLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShuttleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShuttleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShuttleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShuttleApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShuttleApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel backgroundLabel;
    private javax.swing.JTextField carddataField;
    private javax.swing.JLabel deptLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel proceedLabel;
    private javax.swing.JLabel shuttleLabel;
    // End of variables declaration//GEN-END:variables
}
